# Bondad de ajuste

**Ejemplo**. 23 dispositivos mecánicos con sus tiempos de fallo (log-tiempo). ¿Los datos son normales? La hipótesis nula es la normalidad, lo que representa un problema no paramétrico.

## Prueba $\chi^2$

**Datos categóricos**: el rango de la variable asume un número finito de categorías o estados

Suponga que tenemos $k$ categorías,
\[p_i = \mathbb P[\text{Categoría }i],\;i=1,\dotsc,k\]
y $\sum_{i=1}^kp_i = 1$. Sea $p_1^0,\dotsc,p_k^0$ probabilidades propuestas, $\sum_{i=1}^kp_i^0$. Suponga
\[ H_0: p_i = p_i^0\text{ para } i=1,\dots,k\]
\[ H_1: p_i \ne p_i^0\text{ para al menos un }i\]

Suponga una muestra de $n$ elementos. $N_i$ el número de elementos en la categoría $i$, $\sum _{i=1}^kN_i = n$. Note que 
\[(N_1,\dots,N_k)\sim\text{Multinomial}\]

El número esperado de elementos en la celda $i$ es $n\cdot p_i^0$. Si $N_i -np_i^0$ es cercano a 0 para todo $i$, es indicador de que $H_0$ es cierto.

El **estadístico $\chi^2$** se define como

\[Q = \sum_{i=1}^k\dfrac{(N_i-np_i^0)^2}{np_i^0}.\]

Cuando $n$ es grande y $k$ es "relativamente" pequeño con respecto a $n$,
\[Q \xrightarrow[H_0]{}\chi^2_{k-1}.\]

En la prueba $\chi^2$, $\delta$: Rechazo $H_0$ si $Q\geq c$. Dado un nivel de significancia $\alpha_0$,
\[\mathbb P_{H_0}[Q\geq c]\le \alpha_0\implies c = F^{-1}_{\chi^2_{k-1}}(1-\alpha_0)\]

**Reglas empíricas**

1. La aproximación $(Q\sim\chi^{k-1})$ funciona muy bien si $np_i^0\ge 5$. 

2. La aproximación es buena si $np_i^0\ge 1.5$, $i=1,\dots,k$.

**Ejemplo**: 6004 personas (gente blanca, California)


| $\text{Grupo}$ | $\text{Observado}$ | $\text{Teórico}$ |
|-------|-----------|---------|
|  $\text A$    |$2162$       |$1/3$      |
|$\text B$      |$738$      |$1/8$     |
|$\text {AB}$  |$228$     | $1/24$    |
|$\text O$     |$2876$    |$1/2$   |

Queremos probar $H_0: p_i = p_i^0$, $i=1,2,3,4$.

* $np_1^0 = 6004\cdot1/3 = 2001.3$.

* $np_2^0 = 6004\cdot1/8 = 750.5$.

* $np_3^0 = 6004\cdot1/24 = 250.2$.

* $np_4^0 = 6004\cdot1/2 = 3002$.

\[Q = \dfrac{(2162-2001.3)^2}{2001.3} + \dfrac{(738-750.5)^2}{750.5} + \dfrac{(228-250.2)^2}{250.2} + \dfrac{(2876-3002)^2}{3002} = 20.37.\]

El valor-*p* es $\bar F_{\chi^2_3(20.37)} = 1.42\times 10^{-4}$.

Rechazamos la hipótesis de que las probabilidades teóricas de tipo de sangre son igual al valor hipotético.

**Ejemplo**. Sean $0<X_i<1$, $i=1,2,\dots,100$. $X_i~f$, $f$ una densidad continua.

\[H_0: f=\text{Unif}(0,1) \text{ vs } H_1: f \ne\text{Unif}(0,1). \]

Se definen 20 niveles, que corresponden a intervalos de [0,1]. Una observación $X_j$ está en el nivel $i$ si 
\[\dfrac{i-1}{20}\leq X_j <\dfrac{i}{20}\].

| $\text{Nivel}$ | $1$ | $2$ | $\cdots$ | $20$|
|---------------|-------|-----|-------|--------|
| $\text{Frecuencia}$ | $N_1$ | $N_2$ | $\cdots$ | $N_{20}$|

donde $N_i$ es el número de observaciones que están en el intervalo $i$.

|$i$|$X_i$|$\text{Grupo}$|
|---|-----|--------------|
| $1$ |$X_1$ | $2$|
| $2$ |$X_2$ | $4$|
| $3$ |$X_3$ | $17$|
| $\vdots$ |$\vdots$  | $\vdots$ |
| $100$ |$X_{100}$ | $20$|

Las hipótesis anteriores son equivalentes a
\[H_0: p_i = \dfrac{1}{20}, \;i=1,\dots,20.\]

$np_i^0 = 100\cdot\dfrac 1{20} = 5,\;i = 1,\dots,20$.

Entonces
\[Q = \sum_{i=1}^{20}\dfrac{(N_i-5)^2}{5}.\]

Rechazamos la hipótesis $f = \text{Unif}(0,1)$ si $Q>\chi^2_{19}(1-\alpha_0)$.

**Ejemplo**. Trabajemos con el ejemplo de log-tiempo de vida de los dispositivos.

\[H_0: f = N(\ln50,0.25)\]

Seleccione $k$ tal que $p_i^0 = \mathbb P[\text{log-tiempo perteneza al }i\text{-ésimo intervalo}]\geq \dfrac 5{23}\approx \dfrac 14.$ 

Podemos tomar $k = 4$ grupos (intervalos regulares)

1. Grupo 1: $(-\infty,F^{-1}_{H_0}(0.25)] = (-\infty,3.575]$.

2. Grupo 2: $(F^{-1}_{H_0}(0.25),F^{-1}_{H_0}(0.5)] = (3.575,3.912]$.

3. Grupo 3: $(3.912,4.249]$.

4. Grupo 4: $(4.249,+\infty)$.

|$G_1$|$G_2$|$G_3$|$G_4$|
|-----|-----|-----|-----|
|    $3$|   $4$ |    $8$| $8$  |

\[Q = \dfrac{(3-23\cdot1/4)^2}{23\cdot 1/4} +  \dfrac{(4-23\cdot1/4)^2}{23\cdot 1/4}+\dfrac{(8-23\cdot1/4)^2}{23\cdot 1/4} + \dfrac{(8-23\cdot1/4)^2}{23\cdot 1/4}= 3.609.\]

El valor-*p* corresponde a $\bar F_{\chi^2_3}(3.609) = 0.307$.

Con un nivel de 3%, no se rechaza la hipótesis de normalidad bajo esa escogencia de parámetros.

## Pruebas $\chi^2$ con hipótesis parametrizadas 

**Ejemplo**. $H_0: f = N(\mu,\sigma^2)$, ambos desconocidos.

Cada $p_i$ $(i=1,\dots,k)$ se pueden escribir
\[p_i = \pi_i(\theta), \theta = (\theta_1,\dots,\theta_s)\]
Asuma que $s<k-1$. Las entradas de $\theta$ no se pueden escribir como función de ellas mismas. Además $\sum \pi_i(\theta) = 1$.

\[H_0: p_i = \pi_i(\theta)\text{ para algún parámetro }\theta\in \Omega,\;i=1,\dots,k\]
\[H_1: \text{lo anterior no es cierto}\]

El estadístico es 
\[Q = \sum_{i=1}^k\dfrac{[N_i-n\pi_i(\hat\theta)]^2}{n\pi_i(\hat\theta)}\]
con $\hat\theta$ el MLE de $\theta$ usando la distribución de $(N_1,\dots,N_k)$.

**Teorema**. Bajo $H_0$, conforme $n\to \infty$, $Q\to \chi^2_{k-1-s}$.


**Ejemplo**. Considere 3 niveles, $0<\theta<1$.
\[p_1 = \underbrace{\theta^2}_{\pi_1(\theta)},\;p_2 = \underbrace{2\theta(1-\theta)}_{\pi_2(\theta)},\;p_3 = \underbrace{(1-\theta)^2}_{\pi_3(\theta)}.\]

Se observa que \( p_1+p_2+p_3 = \theta^2 + 2\theta (1-\theta +(1-\theta)^2 =[\theta+(1-\theta)]^2 = 1\).

$s = 1$, $\Omega = [0,1]$.

Como la distribución de $(N_1,\dots,N_k)\underset{H_0}{\sim}  \text{Multinomial}(n,p_1,\dots,p_k)$, se obtiene la verosimilitud 

\[L (\theta|N_1,\dots,N_k) = {n \choose {N_1\cdots N_k}}(\pi_1(\theta))^{N_1}\cdots(\pi_k(\theta))^{N_k}\]

\[\ln L \propto N_1\ln\pi_1(\theta)+\cdots+N_k\ln\pi_k(\theta)\]

Retomando el ejemplo,

\begin{align*}
\ln L(\theta) & \propto N_1\ln \theta^2 + N_2 \ln 2\theta(1-\theta) + N_3\ln (1-\theta)^2\\
& = (2N_1+N_2)\ln \theta + (2N_3+N_2)\ln(1-\theta) + N_2\ln 2
\end{align*}

\[\dfrac{\partial \ln L(\theta)}{\partial\theta} = \dfrac{2N_1+N_2}{\theta}-\dfrac{2N_3+N_2}{1-\theta} = 0 \implies \hat\theta = \dfrac{2N_1+N_2}{2n}\]

Con esto se calcula $\pi_1(\hat \theta)$,$\pi_2(\hat \theta)$,$\pi_3(\hat \theta)$ y $Q$.

**Ejemplo** (Normalidad). Sean $X_1,\dots,X_n\sim f$, $H_0: f = N(\mu,\sigma^2)$ donde $\mu$ y $\sigma^2$ son desconocidos.

Usando la misma partición (en cuartiles)

\[\pi_i(\mu,\sigma^2) = \int_{a_i}^{b_i}(2\pi\sigma^2)^{-1/2}\exp\left(-\dfrac 1{2\sigma^2}(x-\mu)^2\right)dx = \Phi\left(\dfrac{b_i-\mu}{\sigma}\right)-\Phi\left(\dfrac{a_i-\mu}{\sigma}\right)\]

Asumiendo que la *i*-ésima partición es $(a_i,b_i)$, los intervalos son
\[(-\infty,3.575],(3.575,3.912],(3.912,4.249], (4.249,+\infty).\]

La verosimilitud es
\[\ln L(\mu,\sigma^2) = N_1\ln \pi_1(\mu,\sigma^2)+\cdots+N_4\ln\pi_4(\mu,\sigma^2)\]

y se optimiza numéricamente.

Para otra solución, considere el siguiente teorema:

**Teorema** (1954). $X_1,\dots, X_n\sim F_\theta$, $\theta: p$-dimensional. $\hat\theta_n$ es el MLE de $\theta$ (basado en $X_1,\dots, X_n$). Tome una partición de $\mathbb R$ con $k$ intervalos disjuntos $(I_1,\dots,I_k)$. $N_i$ es la cantidad de $X_i$'s que pertenecen a $I_i$ y $\pi_i(\theta)=\mathbb P_\theta[X_i\in I_i]$,
\[Q' = \sum_{i=1}^k\dfrac{[N_i-n\pi_i(\hat\theta_n)]^2}{n\pi_i(\hat\theta_n)}\]

Bajo las condiciones de regularidad del MLE, si $n\to\infty$, el cdf de $Q'$ bajo $H_0$ está entre $\chi^2_{k-p-1}$ y $\chi^2_{k-1}$.

Del ejemplo anterior (tiempo de vida de los dispositivos), tome $\hat\mu = \bar X_n = 4.15$ y $\hat\sigma^2 = \dfrac{s_n^2}{n} = 0.2722$.

* $\pi_1(\hat\mu,\hat\sigma^2) = \Phi\left(\dfrac{3.575-4.15}{0.2722^{1/2}}\right)-\Phi(-\infty) = 0.135$.

* $\pi_2(\hat\mu,\hat\sigma^2) = \Phi\left(\dfrac{3.912-4.15}{0.2722^{1/2}}\right) - \Phi\left(\dfrac{3.575-4.15}{0.2722^{1/2}}\right) = 0.1888$.

* $\pi_3(\hat\mu,\hat\sigma^2) = \Phi\left(\dfrac{4.249-4.15}{0.2722^{1/2}}\right) - \Phi\left(\dfrac{3.912-4.15}{0.2722^{1/2}}\right) = 0.2511$.

* $\pi_4(\hat\mu,\hat\sigma^2) = 1 - \Phi\left(\dfrac{4.249-4.15}{0.2722^{1/2}}\right) = 0.4251$.

Entonces

\[Q' = \dfrac{(3-23\cdot 0.135)^2}{23\cdot 0.135} + \dfrac{(4-23\cdot 0.1888)^2}{23\cdot 0.1888} + \dfrac{(8-23\cdot 0.2511)^2}{23\cdot 0.2511} +\dfrac{(8-23\cdot 0.4251)^2}{23\cdot 0.4251}  = 1.211.\]

* $\text{valor-}p_1 = \bar F_{\chi^2_{4-2-1}}(1.211) = 0.2711$.

* $\text{valor-}p_2 = \bar F_{\chi^2_{4-1}}(1.211) = 0.7504$.

Rechazamos $H_0$ (hipótesis de normalidad) si $\alpha_0<0.2711$.

**Ejemplo**. Muertes por patadas.

| $\text{Conteos}$ | $0$ | $1$ | $2$ | $3$ |$\ge 4$| $\text{Total}$|
|---------|---|---|---|---|-------|------|
|$\text{Núm. de obs.}$ | $144$|$91$|$32$|$11$|$2$|$280$|

¿Será la variable Poisson?

$H_0: f = \text{Poisson}(\theta), \theta>0$.

El MLE de $\hat\theta$ es

\[\dfrac{0\cdot 144+1\cdot91+2\cdot32+3\cdot 11+2\cdot4}{280} = \dfrac{196}{280} = 0.7\]

* $\pi_1(\hat\theta) = e^{-\hat\theta} = e^{-0.7}=0.4966$.

* $\pi_2(\hat\theta) = \dfrac{e^{-\hat\theta}\hat\theta}{1!} = 0.3476$.

* $\pi_3(\hat\theta) = \dfrac{e^{-\hat\theta}\hat\theta^2}{2!} = 0.1217$.

* $\pi_4(\hat\theta) =  \dfrac{e^{-\hat\theta}\hat\theta^3}{3!} = 0.0283$.

* $\pi_5(\hat\theta) = \bar F_{\text{Poisson}(\hat\theta)}(4) = 0.0058$

\begin{align*}
Q' & = \dfrac{(144-280\cdot0.4966)^2}{280\cdot0.4966}+\dfrac{(91-280\cdot0.3476)^2}{280\cdot0.3476}+\dfrac{(32-280\cdot0.1217)^2}{280\cdot0.1217}\\
& +\dfrac{(11-280\cdot0.0283)^2}{280\cdot0.0283} +\dfrac{(2-280\cdot0.0058)^2}{280\cdot0.0058} = 1.979.
\end{align*}
 
* $\text{valor-}p_1 =\bar  F_{\chi^2_{5-1-1}}(1.979) = 0.5768$.

* $\text{valor-}p_2 = \bar F_{\chi^2_{5-1}}(1.979) = 0.7396$.

*Interpretación*: con un nivel de significancia del 5% no rechazamos la hipótesis Poisson en los datos.
